In [2]:
a=100 
print(a)

100


In [1]:
import numpy as np


In [9]:
arry1=[1, 3,34]

for i in range(1, 11):
    print(i)


1
2
3
4
5
6
7
8
9
10


In [12]:
data =np.random.rand(2,7)

def mulElements(a, b = 2): return a * b 
result=mulElements(3)
print(result)

a = [1, 2, 2, 'python', 4.5]
print(a)

6
[1, 2, 2, 'python', 4.5]


In [6]:
print(data)

[[4.49363420e-02 2.82553985e-01 1.63051777e-02 7.99103252e-01
  7.10636591e-04 9.95865977e-01 3.58535741e-01]
 [2.93868988e-01 9.44069842e-01 3.16256424e-01 4.52670362e-01
  5.31038845e-01 5.94462774e-01 9.45254444e-01]]


In [7]:
datazero=np.zeros((2,5))
print(datazero)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [9]:
zeroarray=np.zeros((2,8),str)
print(zeroarray)

[['' '' '' '' '' '' '' '']
 ['' '' '' '' '' '' '' '']]


In [10]:
zeroarray.shape

(2, 8)

In [11]:
np.delete?

Signature:       np.delete(arr, obj, axis=None)
Call signature:  np.delete(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function delete at 0x10ee4c790>
File:            ~/Library/Python/3.9/lib/python/site-packages/numpy/lib/function_base.py
Docstring:      
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
`arr[obj]`.

Parameters
----------
arr : array_like
    Input array.
obj : slice, int or array of ints
    Indicate indices of sub-arrays to remove along the specified axis.

    .. versionchanged:: 1.19.0
        Boolean indices are now treated as a mask of elements to remove,
        rather than being cast to the integers 0 and 1.

axis : int, optional
    The axis along which to delete the subarray defined by `obj`.
    If `axis` is None, `obj` is applied to the flattened array.

Returns
-------
out : ndarray
    A copy of `arr` with the elements specified by `obj` remo

In [12]:
randomnum=np.random.rand(10)
print(randomnum)



[0.47971749 0.97353984 0.8999427  0.39468533 0.65798444 0.71228167
 0.54842992 0.5683299  0.6380557  0.33708336]


In [13]:
np.delete(randomnum,1)

array([0.47971749, 0.8999427 , 0.39468533, 0.65798444, 0.71228167,
       0.54842992, 0.5683299 , 0.6380557 , 0.33708336])

In [14]:
import pandas as pd 
diab=pd.read_csv('./diabetes.csv')

diab.head()
diab.tail(10)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
758           1    106.0             76              0      NaN  37.5   
759           6    190.0             92              0      NaN  35.5   
760           2     88.0             58             26      NaN  28.4   
761           9    170.0             74             31      NaN  44.0   
762           9     89.0             62              0      NaN  22.5   
763          10    101.0             76             48      NaN  32.9   
764           2    122.0             70             27      NaN  36.8   
765           5    121.0             72             23      NaN  26.2   
766           1    126.0             60              0      NaN  30.1   
767           1     93.0             70             31      NaN  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
758                     0.197   26        0  
759                     0.278   66        1  
760                     0.766   22        0  
761                     0.403   43        1  
762                     0.142   33        0  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0

In [15]:
diab.describe


<bound method NDFrame.describe of     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             6    148.0             72             35      NaN  33.6   
1             1     85.0             66             29      NaN  26.6   
2             8    183.0             64              0      NaN  23.3   
3             1     89.0             66             23     94.0  28.1   
4             0    137.0             40             35    168.0  43.1   
..          ...      ...            ...            ...      ...   ...   
763          10    101.0             76             48      NaN  32.9   
764           2    122.0             70             27      NaN  36.8   
765           5    121.0             72             23      NaN  26.2   
766           1    126.0             60              0      NaN  30.1   
767           1     93.0             70             31      NaN  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627  999        1

In [16]:
diab.columns


Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [17]:
diab.dtypes

Pregnancies                  object
Glucose                     float64
BloodPressure                 int64
SkinThickness                 int64
Insulin                     float64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [18]:
diab[['Pregnancies','Glucose']].head(3)

Pregnancies  Glucose
0           6    148.0
1           1     85.0
2           8    183.0

In [19]:
print('#fech rows')
print(diab[2:4])
#fetch data at specific row and column
print(diab.iloc[2,4])
#fetch null values 
print(diab.isnull().sum())

#fech rows
  Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
2           8    183.0             64              0      NaN  23.3   
3           1     89.0             66             23     94.0  28.1   

   DiabetesPedigreeFunction  Age  Outcome  
2                     0.672   32        1  
3                     0.167   21        0  
nan
Pregnancies                   0
Glucose                       5
BloodPressure                 0
SkinThickness                 0
Insulin                     535
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64


In [21]:
#drop a column
print(diab.drop(columns='Insulin', axis=1))
print(diab.shape)
diab["name"]=diab["Age"]*diab['BMI']
print(diab)
diab.head()

    Pregnancies  Glucose  BloodPressure  SkinThickness   BMI  \
0             6    148.0             72             35  33.6   
1             1     85.0             66             29  26.6   
2             8    183.0             64              0  23.3   
3             1     89.0             66             23  28.1   
4             0    137.0             40             35  43.1   
..          ...      ...            ...            ...   ...   
763          10    101.0             76             48  32.9   
764           2    122.0             70             27  36.8   
765           5    121.0             72             23  26.2   
766           1    126.0             60              0  30.1   
767           1     93.0             70             31  30.4   

     DiabetesPedigreeFunction  Age  Outcome  name  
0                       0.627  999        1  1099  
1                       0.351   31        0   131  
2                       0.672   32        1   132  
3                      

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0           6    148.0             72             35      NaN  33.6   
1           1     85.0             66             29      NaN  26.6   
2           8    183.0             64              0      NaN  23.3   
3           1     89.0             66             23     94.0  28.1   
4           0    137.0             40             35    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome     name  
0                     0.627  999        1  33566.4  
1                     0.351   31        0    824.6  
2                     0.672   32        1    745.6  
3                     0.167   21        0    590.1  
4                     2.288   33        1   1422.3